Translation: refine wording in default language
ElderDrivers/EdXposedManager pull request #136
Opened 2020-10-01 14:49 UTC by HankAviator

_If your pull request is a translation update, then the title of this pull must contains 'string' or 'translation'_

2020-10-01 15:10 UTC, MlgmXyysd requested changes

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="settings_summary_black_white_list">When enabled, you can apply a list in \"Xposed Hide\"\nXposed Hide(Blacklist): Selected apps will NOT load EdXposed modules\nNote: using Xposed Hi
Blacklist mode -> Xposed Hide (black)
Whitellist mode -> Xposed Hide (White)

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="settings_summary_pass_safetynet">Force add GMS and GSF to blacklist and remove from whitelist\nDisabling this option does not remove modules from blacklist\nXposed Hide is required<
Blacklist mode -> Xposed Hide(black)

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="reboot_edl">Reboot to EDL</string>
This mode has many aliases, such as EDL and 9008, and E is Emergency, so I prefer to use Emergency or Emergency Mode

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="title_white_list">Whitelist</string>
ditto

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="title_black_list">Blacklist</string>
ditto

2020-10-01 15:10 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="hook_modules_summary">Force add modules to whitelist and remove from blacklist\nDisabling this option does not remove modules from blacklist\nXposed Hide is required</string>
ditto

2020-10-01 15:24 UTC, HankAviator commented on app/src/main/res/values/strings.xml
> +    <string name="settings_summary_black_white_list">When enabled, you can apply a list in \"Xposed Hide\"\nXposed Hide(Blacklist): Selected apps will NOT load EdXposed modules\nNote: using Xposed Hi
Xposed Hide(Blacklist) -> Xposed Hide(Black) 

What about `black-list` and `white-list`? Do you want to keep them as-is?

2020-10-01 15:30 UTC, MlgmXyysd commented on app/src/main/res/values/strings.xml
> +    <string name="settings_summary_black_white_list">When enabled, you can apply a list in \"Xposed Hide\"\nXposed Hide(Blacklist): Selected apps will NOT load EdXposed modules\nNote: using Xposed Hi
> Xposed Hide(Blacklist) -> Xposed Hide(Black)
> 
> What about `black-list` and `white-list`? Do you want to keep them as-is?

just change to `Xposed Hide (Black/White)`

2020-10-01 15:37 UTC, HankAviator commented
Wait, forgot a commit.

2020-11-06 14:58 UTC, MlgmXyysd commented
Changes merged in https://github.com/ElderDrivers/EdXposedManager/commit/9bcf859709c1159f7f11e9fe6df713e14596f8f4

2020-11-06 14:58 UTC, closed without merging